steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/my-image:${SHORT_SHA}",
        ".",
      ]
    id: "Build Container Image"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/my-image:${SHORT_SHA}",
      ]
    id: "Push Image to artifact repository"

  - name: google/cloud-sdk
    args:
      [
        "gcloud",
        "run",
        "deploy",
        "cours-representation-information",
        "--image=us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/my-image:${SHORT_SHA}",
        "--region",
        "europe-west6",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
    id: "Deploy conteiner on Google Cloud Run"

options:
  logging: CLOUD_LOGGING_ONLY
